spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inheritanceMapping
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      auto_quote_keyword: true

    defer-datasource-initialization: true

    database-platform: org.hibernate.dialect.MySQLDialect


  server:
    port: 8080




